### ISSUE TITLE
new make_report argument

### ISSUE THREAD

**Issue by romainkp** [romainkp/stremr#18]
Currently, a call to make_report_rmd leads to a browser or a pdf reader to open up automatically and display the report of analysis results. This is problematic when make_report_rmd is called several times from a larger program and one ends up with a cluttered desktop. 

Is it possible to add an argument that prevents the pop-up of the display windows?

**Comment by osofr** [comment]
Argument `openFile` to `make_report_rmd()` now allows this as of latest commit.
