### ISSUE TITLE
stremr output

### ISSUE THREAD

**Issue by marycombs** [romainkp/stremr#39]
Can you help me understand the output of stremr? In the optimal dynamic treatment rule example, in the output table IPW_estimates, there are the variables: sum_Y_IPAW,  sum_all_IPAW, ht, St.IPTW, ht.KM. Can you help me understand how to interpret each of these variables?

**Comment by osofr** [comment]
Please let me know which specific functions you are running. 

As far as the variables above are involved, it appears that these are the output of `survNPMSM`

Here are the relevant variables defined in the source code: 

https://github.com/osofr/stremr/blob/e6cd51cea0531883cd195ed61f6f72b93b45528b/R/main_estimation.R#L842
Sum of the weighted outcomes (Y multiplied by propensity score cumulative weight), by time-point

https://github.com/osofr/stremr/blob/e6cd51cea0531883cd195ed61f6f72b93b45528b/R/main_estimation.R#L846
Sum of the cumulative propensity scores, by time-point.

The rest of the definitions of the variables can be found similarly, by browsing the function. Briefly, `ht` is the IPW-hazard, by time-point, `St.IPTW` is the IPW estimator obtained from that hazard, `ht.KM` is the Kaplan-Meier hazard.
